---
- name:  Configure Spinet server
  hosts: spinet

  become:      yes
  become_user: root

  pre_tasks:
    - name: Update cache if needed
      apt:
        update_cache:     yes
        cache_valid_time: 3600

  roles:
    - name: viget.base
      tags: base

    - name: viget.firewall
      tags: firewall

    - name: viget.deploy
      tags: deploy

    - name: viget.imagemagick
      tags: imagemagick

    - name: viget.ruby
      tags: ruby

    - name: viget.postgresql
      tags: postgresql

    - name: viget.ssl
      tags: ssl

    - name: viget.nginx
      tags: nginx

    - name: viget.rails
      tags: rails

  tasks:
    - name: Install libvips
      apt:
        name: libvips
        state: present

    - name: Add db password to nginx env
      blockinfile:
        path: /etc/default/nginx
        state: absent
        block: |
          export NAME_PICKER_DATABASE_PASSWORD="{{ vault.postgres.users.app.password }}"
      notify: reload nginx
      tags: rails

    - name: Add db password to deploy user bashrc
      blockinfile:
        path: "{{ deploy_user_home }}/.bashrc"
        state: absent
        block: |
          export NAME_PICKER_DATABASE_PASSWORD="{{ vault.postgres.users.app.password }}"
      tags: rails
