name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:14.7
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: standardrb
        run: bundle exec standardrb
      - name: Run tests
        run: bundle exec rspec
